// src/peptides.js
// Katalys Health — Peptide Knowledge Base
// All strings use single quotes. Apostrophes inside strings are escaped.
// No em-dashes, arrows, or special unicode inside JS string literals.
// Updated: May 2026

export const OPTIMIZATION_GOALS = [
  { id: 'recovery',     label: 'Injury Recovery',    icon: '🔄' },
  { id: 'muscle_mass',  label: 'Muscle & Strength',  icon: '💪' },
  { id: 'fat_loss',     label: 'Fat Loss',            icon: '🔥' },
  { id: 'longevity',    label: 'Longevity',           icon: '⏳' },
  { id: 'gut_health',   label: 'Gut & GI Health',     icon: '🌿' },
  { id: 'cognitive',    label: 'Mental Clarity',      icon: '🧠' },
  { id: 'immune',       label: 'Immune Support',      icon: '🛡️' },
  { id: 'mitochondria', label: 'Energy & Mito',       icon: '⚡' },
  { id: 'sexual',       label: 'Sexual Health',       icon: '💚' },
  { id: 'anti_aging',   label: 'Anti-Aging / Skin',  icon: '✨' },
  { id: 'sleep',        label: 'Sleep Quality',       icon: '🌙' },
  { id: 'hormone',      label: 'Hormone Optimization',icon: '⚗️' },
];

export const PEPTIDE_KNOWLEDGE_BASE = [

  {
    id: 'bpc157',
    name: 'BPC-157',
    fullName: 'Body Protection Compound 157',
    categoryTag: 'healing',
    category: 'Healing & Cytoprotection',
    icon: '🔄',
    tagline: 'The most studied healing peptide in clinical use',
    regulatoryStatus: 'Category 1 — Compoundable by prescription (Feb 2026)',
    researchLevel: 'moderate',
    isResearchOnly: false,
    summary: 'Synthetic 15-amino-acid pentadecapeptide isolated from human gastric juice. Over 200 preclinical publications. Heals tendons, ligaments, GI tract, burns, and nerve tissue via angiogenesis, nitric oxide modulation, and growth hormone receptor upregulation.',
    mechanism: 'VEGFR2 upregulation (angiogenesis). NO/eNOS modulation. FAK-paxillin pathway. Growth hormone receptor upregulation in fibroblasts (7x by day 3). EGR-1/NAB2 collagen expression. Dopamine and serotonin system modulation.',
    benefits: [
      'Accelerates tendon, ligament, and muscle healing',
      'Heals GI tract: ulcers, IBD, fistulas, NSAID damage',
      'Burn wound healing — outperforms silver sulfadiazine in animal models',
      'Optimizes vascular response across endothelium',
      'Neuroprotection: TBI, sciatic nerve, spinal cord injury',
      'Reduces IL-6, TNF-alpha, LTB4, TXB2, MPO',
      'Interstitial cystitis: 10/12 patients 100% resolved (Lee 2024)',
    ],
    dosing: {
      typical: '250-500 mcg/day SC',
      range: '250-1000 mcg/day',
      frequency: 'Once or twice daily',
      route: ['Subcutaneous', 'Intramuscular', 'Oral (GI indications only)'],
      cycle: '4-6 weeks on, 2-4 weeks off',
      notes: 'Acute injury: 500 mcg BID x 2 weeks, then taper. GI: oral BID. Take away from food for oral use.',
    },
    sideEffects: 'Well-tolerated. Mild injection-site irritation. Transient fatigue in first few days (~10%). No serious adverse events in 500,000+ prescriptions.',
    stacks: ['BPC-157 + TB-500 (Wolverine Stack)', 'BPC-157 + CJC-1295/Ipamorelin (GH axis amplification)', 'BPC-157 + KPV (gut healing)', 'BPC-157 + GHK-Cu (skin and wound healing)'],
    humanEvidence: '3 published human studies: IV safety pilot (Lee 2025, n=2), interstitial cystitis pilot (Lee 2024, n=12, 10/12 resolved), knee pain (Lee 2021, n=16, 14/16 relief). Phase II UC trial (Ruenzi 2005) showed trend but not statistically significant vs placebo.',
    pkHalfLife: 'Less than 30 min',
    bioavailability: 'IM: 14-19% (rats), 45-51% (dogs)',
    researchSources: 'Sikiric P et al, Current Pharmaceutical Design 2018; Lee E et al, PMID 38829631; Ruenzi M et al, Inflamm Bowel Dis 2005',
  },

  {
    id: 'tb500',
    name: 'TB-500',
    fullName: 'Thymosin Beta-4',
    categoryTag: 'healing',
    category: 'Healing & Recovery',
    icon: '⚡',
    tagline: 'Systemic tissue repair and anti-inflammatory agent',
    regulatoryStatus: 'Research peptide — not FDA-approved',
    researchLevel: 'moderate',
    isResearchOnly: true,
    summary: 'Synthetic fragment of Thymosin Beta-4. Promotes cell migration, angiogenesis, and systemic anti-inflammation. Most commonly paired with BPC-157 in the Wolverine Stack for synergistic tissue repair.',
    mechanism: 'Actin G-monomer sequestration. Cell migration via FAK. MMP upregulation. NF-kB anti-inflammatory suppression. Angiogenesis stimulation.',
    benefits: [
      'Accelerated muscle, tendon, and ligament repair',
      'Systemic anti-inflammatory effects',
      'Cardiac tissue repair post-injury',
      'Neurite outgrowth support',
      'Hair follicle stimulation',
    ],
    dosing: {
      typical: '2-2.5 mg twice weekly SC',
      range: '2-5 mg/week',
      frequency: 'Twice weekly (loading), weekly (maintenance)',
      route: ['Subcutaneous', 'Intramuscular'],
      cycle: '4-6 weeks loading, then maintenance or 4-week break',
      notes: 'Stack with BPC-157 for maximum healing synergy (Wolverine Stack).',
    },
    sideEffects: 'Generally well-tolerated. Mild fatigue reported anecdotally. Limited long-term human data.',
    stacks: ['TB-500 + BPC-157 (Wolverine Stack — most common healing combination)'],
    humanEvidence: 'Limited human data. Primarily animal studies. Widely used in clinical practice based on preclinical evidence.',
    pkHalfLife: 'Approximately 2 hours',
    bioavailability: 'IM: high',
    researchSources: 'Goldstein AL et al, Ann N Y Acad Sci 2012; Smart N et al, Nature 2007',
  },

  {
    id: 'cjc1295',
    name: 'CJC-1295',
    fullName: 'CJC-1295 (GHRH Analogue)',
    categoryTag: 'gh_axis',
    category: 'GH Axis',
    icon: '📈',
    tagline: 'Long-acting GHRH analogue — sustained GH and IGF-1 elevation',
    regulatoryStatus: 'Compoundable by prescription. Not FDA-approved.',
    researchLevel: 'moderate',
    isResearchOnly: false,
    summary: 'Modified GHRH analogue that binds albumin (Cys34) via DAC technology, extending half-life from minutes to 5-8 days. Produces sustained 2-10x increases in GH and 44-45% increases in IGF-1 (P less than 0.001) while preserving natural GH pulsatility.',
    mechanism: 'GHRH receptor agonism on pituitary somatotrophs. Albumin binding via DAC extends half-life to 5.8-8.1 days. Increases GH mRNA 11-fold with daily dosing. Preserves physiological GH pulsatility — not supraphysiologic blunting.',
    benefits: [
      'GH increase 2-10x sustained for 6+ days (single dose)',
      'IGF-1 increase 44-45% (P less than 0.001) sustained',
      'Preserves natural GH pulse architecture',
      'Muscle gain and fat loss via improved GH/IGF-1 axis',
      'Recovery and sleep quality improvement',
      'Anti-aging effects on body composition',
    ],
    dosing: {
      typical: '1-2 mg SC once weekly (with DAC)',
      range: '1-2 mg/week (DAC) or 100-300 mcg daily (no DAC)',
      frequency: 'Weekly (DAC form) or daily (no DAC form)',
      route: ['Subcutaneous'],
      cycle: '3-6 months then break to preserve pituitary sensitivity',
      notes: 'CJC-1295 with DAC (weekly dosing) vs CJC-1295 without DAC (paired with Ipamorelin, dosed daily at bedtime). Most practitioners prefer the no-DAC form for preserved pulsatility.',
    },
    sideEffects: 'Water retention, joint aches, mild tingling — all GH-related and dose-dependent. No cortisol, prolactin, or TSH effects confirmed in human PK studies.',
    stacks: ['CJC-1295 + Ipamorelin (synergistic GH pulse — most common GH stack)', 'CJC-1295 + BPC-157 (BPC upregulates GHR)', 'CJC-1295 + AOD-9604 (GH axis + direct fat loss)'],
    humanEvidence: '4 peer-reviewed human studies: Teichman 2006 (JCEM, half-life 5.8-8.1 days, GH 2-10x), Ionescu and Frohman 2006 (JCEM, IGF-1 +44%, P less than 0.001), Alba et al 2006 (Am J Physiol, GH mRNA 11-fold), Jette 2005 (albumin binding mechanism).',
    pkHalfLife: '5.8-8.1 days (with DAC); 30 minutes (no DAC)',
    bioavailability: 'SC: greater than 90% with DAC binding; albumin-bound greater than 90%',
    researchSources: 'Teichman SL et al, JCEM 2006;91:799; Ionescu M and Frohman LA, JCEM 2006;91:4792; Alba M et al, Am J Physiol Endocrinol Metab 2006;291:E1290; Jette L et al, JCEM 2005;90:2445',
  },

  {
    id: 'ipamorelin',
    name: 'Ipamorelin',
    fullName: 'Ipamorelin (GHRP-5)',
    categoryTag: 'gh_axis',
    category: 'GH Axis',
    icon: '💉',
    tagline: 'Selective GHRP — clean GH pulse without cortisol',
    regulatoryStatus: 'Compoundable by prescription. Not FDA-approved.',
    researchLevel: 'moderate',
    isResearchOnly: false,
    summary: 'Highly selective 5th-generation GHRH secretagogue (GHRP). Acts at the ghrelin receptor (GHSR) to trigger a clean GH pulse without stimulating ACTH, cortisol, or prolactin. The most selective GHRP available. Almost exclusively used in combination with CJC-1295.',
    mechanism: 'GHSR (ghrelin receptor) agonism on pituitary somatotrophs. Selective for GH release only — no ACTH, cortisol, aldosterone, or prolactin stimulation. Synergistic with GHRH analogues (CJC-1295) to amplify GH pulse 2-10x beyond either agent alone.',
    benefits: [
      'Clean selective GH pulse without cortisol side effects',
      'Improved body composition: muscle gain and fat reduction',
      'Enhanced slow-wave sleep quality',
      'Improved recovery from training and injury',
      'Anti-aging effects on skin, hair, and energy',
      'Appetite stimulation (ghrelin pathway)',
    ],
    dosing: {
      typical: '100-300 mcg SC at bedtime',
      range: '100-300 mcg per dose',
      frequency: 'Once daily (bedtime) or twice daily',
      route: ['Subcutaneous'],
      cycle: '3-6 months, then 4-week break',
      notes: 'Always dose at bedtime to align with natural GH pulse. Combine with CJC-1295 (no DAC) for synergistic effect. Avoid dosing with carbohydrates (blunts GH release).',
    },
    sideEffects: 'Well-tolerated. Mild water retention and joint aches at higher doses. Transient hunger from ghrelin pathway activation. No cortisol or prolactin effects.',
    stacks: ['Ipamorelin + CJC-1295 (no DAC) — the standard GH stack', 'Ipamorelin + BPC-157 (recovery and GH axis)'],
    humanEvidence: 'Limited direct human RCT data. Animal studies robust. Widely used in clinical anti-aging practice. Safety established from clinical use.',
    pkHalfLife: 'Approximately 2 hours',
    bioavailability: 'SC: 70-90%',
    researchSources: 'Raun K et al, Eur J Endocrinol 1998;139:552; Bowers CY, J Pediatr Endocrinol Metab 1993',
  },

  {
    id: 'cjc_ipamorelin',
    name: 'CJC-1295 + Ipamorelin',
    fullName: 'CJC-1295 / Ipamorelin Stack',
    categoryTag: 'gh_axis',
    category: 'GH Axis',
    icon: '💪',
    tagline: 'Synergistic GH pulse — GHRH + GHRP combination',
    regulatoryStatus: 'Compoundable by prescription. Not FDA-approved.',
    researchLevel: 'moderate',
    isResearchOnly: false,
    summary: 'The most common GH-axis peptide stack. CJC-1295 (GHRH analogue) elevates baseline GH; Ipamorelin (selective GHRP) amplifies the pulse without cortisol or prolactin side effects. Together produce 2-10x greater GH output than either alone.',
    mechanism: 'CJC-1295: GHRH receptor agonism on pituitary somatotrophs. Ipamorelin: GHSR (ghrelin receptor) agonism — selective, no ACTH or cortisol stimulation. Dual-pathway synergy maximizes GH pulse amplitude while preserving pulsatility.',
    benefits: [
      'Increased GH and IGF-1 levels — 2-10x synergistic amplification',
      'Improved body composition: muscle gain and fat loss',
      'Enhanced recovery and slow-wave sleep quality',
      'Anti-aging effects on skin, hair, and energy',
      'Joint and connective tissue improvement',
    ],
    dosing: {
      typical: 'CJC-1295 (no DAC) 100-300 mcg + Ipamorelin 100-300 mcg together at bedtime SC',
      range: '100-300 mcg each per dose',
      frequency: 'Daily at bedtime (no DAC) or weekly CJC-1295 DAC + daily Ipamorelin',
      route: ['Subcutaneous (both peptides)'],
      cycle: '3-6 months, then 4-8 week break to preserve pituitary sensitivity',
      notes: 'Dose together 60 min after last meal. Avoid carbohydrates before dosing. Bedtime timing aligns with natural GH pulse.',
    },
    sideEffects: 'Water retention, joint aches, tingling — GH-related and dose-dependent. Generally mild and resolve with dose reduction.',
    stacks: ['CJC-1295/Ipamorelin + BPC-157 (BPC upregulates GHR, amplifying GH effect)', 'CJC-1295/Ipamorelin + AOD-9604 (GH axis + direct fat loss)'],
    humanEvidence: 'CJC-1295 human PK data published (Teichman 2006). Ipamorelin: animal plus limited human data. Stack widely used in clinical anti-aging practice.',
    pkHalfLife: 'CJC (no DAC): 30 min; CJC (DAC): 5.8-8.1 days; Ipamorelin: approximately 2 hours',
    bioavailability: 'SC: 70-90%',
    researchSources: 'Teichman SL et al, JCEM 2006;91:799; Raun K et al, Eur J Endocrinol 1998',
  },

  {
    id: 'sermorelin',
    name: 'Sermorelin',
    fullName: 'Sermorelin (GHRH 1-29)',
    categoryTag: 'gh_axis',
    category: 'GH Axis',
    icon: '🌱',
    tagline: 'Bioidentical GHRH — the most physiologic GH secretagogue',
    regulatoryStatus: 'FDA-approved for GH deficiency in children (Geref). Compoundable for adults.',
    researchLevel: 'high',
    isResearchOnly: false,
    summary: 'Synthetic analogue of the first 29 amino acids of endogenous GHRH. The most physiologically natural GH secretagogue — stimulates GH release in a pulsatile, feedback-regulated manner. Widely used for adult GH optimization and anti-aging.',
    mechanism: 'GHRH receptor agonism on anterior pituitary somatotrophs. Stimulates GH in a pulsatile, feedback-regulated manner unlike exogenous GH. Preserves hypothalamic-pituitary axis integrity. Does not suppress endogenous GHRH production.',
    benefits: [
      'Increases GH and IGF-1 in a physiologic pulsatile pattern',
      'Improved body composition: lean mass gain, fat reduction',
      'Enhanced sleep quality — increases slow-wave sleep',
      'Improved energy, recovery, and sense of well-being',
      'Bone mineral density support',
      'Safer long-term profile than exogenous GH',
    ],
    dosing: {
      typical: '200-300 mcg SC at bedtime',
      range: '100-500 mcg/day',
      frequency: 'Daily at bedtime',
      route: ['Subcutaneous'],
      cycle: 'Continuous or 3-6 months with 1-2 month break',
      notes: 'Dose at bedtime on empty stomach. Effects develop gradually over 3-6 months. Monitor IGF-1 every 3-6 months to confirm response.',
    },
    sideEffects: 'Generally well-tolerated. Mild flushing or warmth at injection site. Rare: headache, dizziness. No significant cortisol or prolactin effects.',
    stacks: ['Sermorelin + Ipamorelin (GHRH + GHRP synergy, gentler than CJC-1295 stack)', 'Sermorelin + BPC-157 (recovery and GH axis)'],
    humanEvidence: 'FDA-approved with clinical trial data. Multiple studies demonstrating GH and IGF-1 increases in adults. Long clinical safety record.',
    pkHalfLife: '10-20 minutes',
    bioavailability: 'SC: high',
    researchSources: 'Walker RF, Clin Interv Aging 2006;1:307; FDA NDA for Geref (sermorelin acetate)',
  },

  {
    id: 'tesamorelin',
    name: 'Tesamorelin',
    fullName: 'Tesamorelin (Egrifta)',
    categoryTag: 'gh_axis',
    category: 'GH Axis / Metabolic',
    icon: '🎯',
    tagline: 'FDA-approved GHRH analogue for visceral fat reduction',
    regulatoryStatus: 'FDA-approved (Egrifta) for HIV-associated lipodystrophy',
    researchLevel: 'high',
    isResearchOnly: false,
    summary: 'Stabilized GHRH analogue with FDA approval for visceral adiposity reduction in HIV-associated lipodystrophy. Reduces visceral fat by 15-20% in clinical trials. Under investigation for cognitive benefits in MCI and Alzheimer\'s disease.',
    mechanism: 'GHRH receptor agonism on pituitary somatotrophs. Increases GH pulse amplitude and IGF-1. Direct lipolytic effects on visceral adipose tissue. Emerging evidence for neuroprotective effects via IGF-1 in the brain.',
    benefits: [
      'Visceral fat reduction 15-20% (FDA trial data)',
      'Trunk fat and waist circumference reduction',
      'IGF-1 normalization',
      'Lipid profile improvement',
      'Potential cognitive benefits in MCI (under investigation)',
    ],
    dosing: {
      typical: '1-2 mg SC once daily',
      range: '1-2 mg/day',
      frequency: 'Once daily at bedtime',
      route: ['Subcutaneous'],
      cycle: 'Continuous for approved indication; 6-month cycles off-label',
      notes: 'FDA dose is 2 mg daily for lipodystrophy. Off-label anti-aging use often uses 1 mg daily. Monitor fasting glucose — mild insulin resistance risk.',
    },
    sideEffects: 'Injection site reactions, arthralgia, edema. Mild insulin resistance — monitor glucose. Contraindicated in active malignancy.',
    stacks: ['Tesamorelin + Ipamorelin (amplified GH pulse)', 'Tesamorelin + BPC-157 (visceral fat reduction + healing)'],
    humanEvidence: 'Multiple FDA Phase III trials (LATS program). Approved in US for HIV lipodystrophy. Cognitive trials ongoing at University of Wisconsin.',
    pkHalfLife: 'Approximately 30-40 minutes',
    bioavailability: 'SC: approximately 4% (highly potent at low bioavailability)',
    researchSources: 'Falutz J et al, NEJM 2007;357:2349; Baker LD et al, JAMA Neurology 2021',
  },

  {
    id: 'kisspeptin10',
    name: 'Kisspeptin-10',
    fullName: 'Kisspeptin-10 (KP-10)',
    categoryTag: 'sexual',
    category: 'Reproductive / Sexual Health',
    icon: '🌸',
    tagline: 'Hypothalamic neuropeptide — master regulator of the reproductive axis',
    regulatoryStatus: 'Investigational — clinical trials completed. Not FDA-approved.',
    researchLevel: 'high',
    isResearchOnly: true,
    summary: 'Endogenous hypothalamic neuropeptide that activates the HPG axis via GnRH pulse stimulation. Regulates LH, FSH, and sex hormone production. Studied for hypogonadotropic hypogonadism, IVF stimulation, and as a non-androgenic sexual function enhancer.',
    mechanism: 'KISS1R (GPR54) agonism on GnRH neurons in the hypothalamus. Drives pulsatile GnRH release, which stimulates LH and FSH from the pituitary, increasing testosterone and estradiol production. Central mechanism distinct from exogenous hormone replacement.',
    benefits: [
      'Stimulates endogenous testosterone production via LH surge',
      'Enhances sexual desire and arousal centrally',
      'Potential IVF ovarian stimulation adjunct',
      'Preserves HPG axis integrity (unlike exogenous TRT)',
      'Antidepressant effects via limbic system activation',
    ],
    dosing: {
      typical: '10-50 mcg SC on-demand or 1 mg intranasally',
      range: '10-100 mcg SC per dose',
      frequency: 'On-demand (sexual function) or pulsatile for hypogonadism',
      route: ['Subcutaneous', 'Intranasal', 'Intravenous (clinical only)'],
      cycle: 'On-demand or short courses of 1-4 weeks',
      notes: 'Requires physician supervision for HPG axis applications. On-demand use for sexual function: 30-60 min before activity. Do not use in patients with sex hormone-responsive cancers.',
    },
    sideEffects: 'Well-tolerated in clinical trials. Mild nausea, flushing. Contraindicated in hormone-sensitive malignancies.',
    stacks: ['Kisspeptin-10 + PT-141 (HPG axis activation + central desire)', 'Kisspeptin-10 + CJC-1295/Ipamorelin (hormonal optimization stack)'],
    humanEvidence: 'Multiple Phase I/II clinical trials at UCSF, Imperial College London. Robust human endocrinology data for HPG axis activation.',
    pkHalfLife: 'Approximately 28 minutes',
    bioavailability: 'SC: high; intranasal: moderate',
    researchSources: 'Dhillo WS et al, J Clin Endocrinol Metab 2005;90:6609; Jayasena CN et al, Clin Endocrinol 2011',
  },

  {
    id: 'pt141',
    name: 'PT-141',
    fullName: 'Bremelanotide (PT-141)',
    categoryTag: 'sexual',
    category: 'Sexual Health',
    icon: '💚',
    tagline: 'Central melanocortin agonist — FDA-approved for HSDD',
    regulatoryStatus: 'FDA-approved as Vyleesi for HSDD in premenopausal women',
    researchLevel: 'high',
    isResearchOnly: false,
    summary: 'Melanocortin receptor agonist acting centrally on the hypothalamus to increase sexual desire. Distinct from PDE5 inhibitors — works via brain, not vascular. On-demand use for both men and women.',
    mechanism: 'MC3R and MC4R agonism in hypothalamus. Dopaminergic and oxytocin pathway activation. Central sexual motivation drive independent of vascular mechanisms.',
    benefits: [
      'Increased sexual desire and arousal in men and women',
      'FDA-approved for HSDD in premenopausal women',
      'Spontaneous erections in men (off-label)',
      'Central mechanism — independent of vascular function',
      'On-demand dosing with no daily requirement',
    ],
    dosing: {
      typical: '1.75 mg SC 45 minutes before activity (FDA dose)',
      range: '0.5-2 mg per dose',
      frequency: 'On-demand, maximum once per 24 hours',
      route: ['Subcutaneous', 'Intranasal (off-label)'],
      cycle: 'On-demand use',
      notes: 'Avoid high-fat meals before dosing. Nausea risk is lower when starting at 0.5-1 mg. FDA-approved dose is 1.75 mg SC.',
    },
    sideEffects: 'Nausea (most common), flushing, headache, transient blood pressure changes, hyperpigmentation with repeated use.',
    stacks: ['PT-141 + Kisspeptin-10 (hormonal + central desire)', 'PT-141 + PDE5 inhibitor (vascular + central)'],
    humanEvidence: 'FDA Phase III trials completed (Simon 2019). Well-established clinical safety and efficacy data. FDA-approved for women.',
    pkHalfLife: 'Approximately 2-3 hours',
    bioavailability: 'SC: approximately 100%',
    researchSources: 'Simon JA et al, Obstet Gynecol 2019;134:899; FDA approval NDA 210557 (Vyleesi)',
  },

  {
    id: 'semaglutide',
    name: 'Semaglutide',
    fullName: 'Semaglutide (GLP-1 RA)',
    categoryTag: 'metabolic',
    category: 'GLP-1 / Metabolic',
    icon: '📊',
    tagline: 'Gold standard GLP-1 agonist — 15-20% weight loss',
    regulatoryStatus: 'FDA-approved (Ozempic, Wegovy, Rybelsus)',
    researchLevel: 'very_high',
    isResearchOnly: false,
    summary: 'Long-acting GLP-1 receptor agonist. The current gold standard for weight management and T2DM treatment. 15-20% body weight reduction in STEP trials. Weekly injection or daily oral tablet.',
    mechanism: 'GLP-1R agonism. Insulin secretion increase. Glucagon suppression. Delayed gastric emptying. Central appetite suppression (hypothalamic). Cardioprotective pathways via GLP-1R on cardiomyocytes.',
    benefits: [
      '15-20% body weight reduction (STEP trials)',
      'HbA1c reduction in T2DM',
      'Cardiovascular risk reduction (SUSTAIN-6)',
      'MASH/NASH liver improvement',
      'Potential neuroprotective effects under investigation',
    ],
    dosing: {
      typical: '0.25 mg/week SC starting, titrate to 2.4 mg/week over 16-20 weeks',
      range: '0.25-2.4 mg/week',
      frequency: 'Once weekly (SC) or once daily (oral)',
      route: ['Subcutaneous injection (weekly)', 'Oral tablet daily (Rybelsus)'],
      cycle: 'Chronic ongoing therapy for weight management or T2DM',
      notes: 'Slow titration minimizes GI side effects. Protein intake and resistance training critical for muscle mass preservation.',
    },
    sideEffects: 'Nausea, vomiting, diarrhea during titration. Rare: pancreatitis, gallbladder disease. Muscle mass loss concern with rapid weight reduction. Monitor thyroid (MTC risk — contraindicated in MEN2).',
    stacks: ['Semaglutide + resistance training + adequate protein (muscle preservation)', 'Semaglutide + BPC-157 sublingual (GI side effect mitigation)'],
    humanEvidence: 'Multiple large RCTs: STEP 1-4 programs, SUSTAIN program. Thousands of participants. FDA-approved for weight loss and T2DM.',
    pkHalfLife: 'Approximately 7 days',
    bioavailability: 'SC: approximately 89%; oral: approximately 1%',
    researchSources: 'Wilding JPH et al, NEJM 2021;384:989 (STEP 1); Marso SP et al, NEJM 2016;375:1834 (SUSTAIN-6)',
  },

  {
    id: 'tirzepatide',
    name: 'Tirzepatide',
    fullName: 'Tirzepatide (GLP-1/GIP Dual Agonist)',
    categoryTag: 'metabolic',
    category: 'GLP-1/GIP / Metabolic',
    icon: '⭐',
    tagline: 'Dual GLP-1/GIP agonist — up to 22% weight loss',
    regulatoryStatus: 'FDA-approved (Mounjaro for T2DM, Zepbound for obesity)',
    researchLevel: 'very_high',
    isResearchOnly: false,
    summary: 'First-in-class dual GLP-1 and GIP receptor agonist. Superior weight loss versus semaglutide in head-to-head SURMOUNT trials — up to 22.5% body weight reduction. Also improves insulin sensitivity, lipids, and cardiovascular markers.',
    mechanism: 'GLP-1R and GIPR co-agonism. GIP receptor activation amplifies insulin secretion and reduces glucagon beyond GLP-1 alone. Synergistic appetite suppression. Superior beta-cell protection. Complementary adipose tissue effects.',
    benefits: [
      'Up to 22.5% body weight reduction (SURMOUNT-1)',
      'Superior to semaglutide in head-to-head weight loss',
      'HbA1c reduction 2.0-2.4% in T2DM',
      'Cardiovascular event reduction (SURMOUNT-MMO)',
      'MASH/NASH improvement',
      'Improved insulin sensitivity and lipid profile',
    ],
    dosing: {
      typical: '2.5 mg/week SC starting, titrate to 5-15 mg/week over 20 weeks',
      range: '2.5-15 mg/week',
      frequency: 'Once weekly SC',
      route: ['Subcutaneous injection (weekly)'],
      cycle: 'Chronic ongoing therapy',
      notes: 'Superior efficacy to semaglutide but similar GI side effect profile. Titrate slowly. Protein and resistance training critical.',
    },
    sideEffects: 'Similar to semaglutide: nausea, vomiting, diarrhea, constipation during titration. Thyroid C-cell tumor risk (rodent data) — contraindicated in MEN2/MTC history.',
    stacks: ['Tirzepatide + resistance training + adequate protein (muscle preservation)'],
    humanEvidence: 'Multiple large Phase III RCTs (SURMOUNT program, SURPASS program). FDA-approved for T2DM (2022) and obesity (2023).',
    pkHalfLife: 'Approximately 5 days',
    bioavailability: 'SC: approximately 80%',
    researchSources: 'Jastreboff AM et al, NEJM 2022;387:205 (SURMOUNT-1); Frías JP et al, NEJM 2021;385:503 (SURPASS-2)',
  },

  {
    id: 'ara290',
    name: 'ARA-290',
    fullName: 'Cibinetide (ARA-290)',
    categoryTag: 'neuroprotection',
    category: 'Neuroprotection & Metabolic',
    icon: '🔬',
    tagline: 'Non-hematopoietic EPO analogue for neuropathic pain',
    regulatoryStatus: 'Investigational — clinical trials completed in sarcoidosis/SFN',
    researchLevel: 'high',
    isResearchOnly: true,
    summary: 'Selectively activates the tissue-protective EPO receptor complex (EPOR/betacR) without stimulating red blood cell production. Strongest clinical evidence for small fiber neuropathy and sarcoidosis-related neuropathic pain.',
    mechanism: 'EPOR/betacR heterodimer activation. Akt/PI3K, JAK2, STAT3 pathways. NF-kB and TNF-alpha suppression. Intraepidermal nerve fiber regeneration. Metabolic improvements via insulin sensitization.',
    benefits: [
      'Significant neuropathic pain reduction (RCT data)',
      'Small nerve fiber regeneration',
      'Improved insulin sensitivity',
      'Anti-inflammatory: reduces TNF-alpha, IL-6',
      'Ischemia-reperfusion protection',
    ],
    dosing: {
      typical: '4 mg once daily SC (clinical trial dose)',
      range: '2-4 mg/day',
      frequency: 'Once daily',
      route: ['Subcutaneous'],
      cycle: '4-12 weeks depending on indication',
      notes: 'Requires physician supervision. Primary indication: small fiber neuropathy and sarcoidosis-related neuropathic pain.',
    },
    sideEffects: 'Well-tolerated in clinical trials. No erythropoietic effects. Injection site reactions minimal.',
    stacks: ['ARA-290 + BPC-157 (nerve and tissue repair combination)'],
    humanEvidence: 'Multiple clinical trials in sarcoidosis and small fiber neuropathy: Culver DA et al (2017), Dahan A et al (2013, 2015). Positive results in RCT designs.',
    pkHalfLife: 'Approximately 3-4 hours',
    bioavailability: 'SC: approximately 60%',
    researchSources: 'Dahan A et al, Mol Med 2013;19:2; Culver DA et al, Pulm Pharmacol Ther 2017;45:110',
  },

  {
    id: 'aod9604',
    name: 'AOD-9604',
    fullName: 'Advanced Obesity Drug 9604',
    categoryTag: 'metabolic',
    category: 'Metabolic & Fat Loss',
    icon: '⚖️',
    tagline: 'hGH lipolytic fragment without IGF-1 effects',
    regulatoryStatus: 'FDA GRAS status for food use. Compoundable.',
    researchLevel: 'moderate',
    isResearchOnly: false,
    summary: 'C-terminal fragment of hGH (residues 176-191). Retains fat-burning properties of GH without IGF-1 stimulation, insulin resistance, or growth side effects. Also studied for cartilage and osteoarthritis repair.',
    mechanism: 'Beta-adrenergic receptor lipolysis stimulation. Lipogenesis inhibition (IGF-1 independent). Proteoglycan synthesis in cartilage. Chondrocyte differentiation support.',
    benefits: [
      'Visceral and subcutaneous fat reduction',
      'No effect on blood glucose or insulin sensitivity',
      'Cartilage regeneration in osteoarthritis models',
      'Improved lipid profile',
    ],
    dosing: {
      typical: '300-500 mcg once daily SC',
      range: '300-500 mcg/day',
      frequency: 'Once daily, fasted AM or pre-exercise',
      route: ['Subcutaneous', 'Oral (limited bioavailability)'],
      cycle: '8-12 weeks, assess results',
      notes: 'Best results when combined with caloric deficit and exercise. No effect on IGF-1 or growth hormone axis.',
    },
    sideEffects: 'Exceptionally well-tolerated. No growth or IGF-1 side effects. No insulin resistance.',
    stacks: ['AOD-9604 + CJC-1295/Ipamorelin (fat loss + GH axis)', 'AOD-9604 + BPC-157 (intra-articular for OA — physician only)'],
    humanEvidence: 'Phase II/III human trials for obesity. Safe in all studies. FDA GRAS status.',
    pkHalfLife: 'Approximately 30 minutes',
    bioavailability: 'SC: approximately 90%',
    researchSources: 'Ng FM et al, J Mol Endocrinol 2000;26:119; Heffernan MA et al, FASEB J 2001',
  },

  {
    id: 'ghkcu',
    name: 'GHK-Cu',
    fullName: 'Copper Peptide GHK-Cu',
    categoryTag: 'anti_aging',
    category: 'Skin & Anti-Aging',
    icon: '✨',
    tagline: 'Copper tripeptide — collagen synthesis and skin renewal',
    regulatoryStatus: 'GRAS in cosmetics. Compoundable for injectable use.',
    researchLevel: 'moderate',
    isResearchOnly: false,
    summary: 'Naturally occurring copper-binding tripeptide (Gly-His-Lys). Drives collagen and elastin synthesis, wound healing, and antioxidant pathways. Used in both topical cosmeceuticals and injectable anti-aging protocols.',
    mechanism: 'Copper chelation activates superoxide dismutase (SOD). Collagen and elastin synthesis increase. VEGF, FGF, TGF-beta upregulation. TNF-alpha and IL-1 suppression. Hair follicle activation.',
    benefits: [
      'Skin collagen and elastin synthesis',
      'Wound healing acceleration',
      'Hair follicle stimulation and regrowth support',
      'Systemic anti-inflammatory activity',
      'Antioxidant via SOD activation',
    ],
    dosing: {
      typical: '1-2 mg/day SC or topical application',
      range: '0.5-3 mg/day SC; topical 1-5% serums twice daily',
      frequency: 'Daily (injectable) or twice daily (topical)',
      route: ['Subcutaneous', 'Topical cream or serum'],
      cycle: '8-12 weeks injectable; topical can be ongoing',
      notes: 'Topical is the most common route. Injectable adds systemic anti-aging effects beyond skin.',
    },
    sideEffects: 'Excellent safety profile. Topical: mild irritation possible. Systemic: minimal reported adverse effects. Copper toxicity is theoretical only at clinical doses.',
    stacks: ['GHK-Cu + BPC-157 (wound and skin healing)', 'GHK-Cu + Epithalon (comprehensive anti-aging protocol)'],
    humanEvidence: 'Primarily in vitro and animal data. Extensive cosmeceutical human data for topical use. Limited injectable human trials.',
    pkHalfLife: 'Approximately 1 hour',
    bioavailability: 'SC: high; topical: 3-5% skin penetration',
    researchSources: 'Pickart L et al, Biomolecules 2015;5:1552; Cangul IT et al, Vet Dermatol 2004',
  },

  {
    id: 'epithalon',
    name: 'Epithalon',
    fullName: 'Epithalamin / Epithalon',
    categoryTag: 'longevity',
    category: 'Longevity & Anti-Aging',
    icon: '⏳',
    tagline: 'Telomerase-activating tetrapeptide from the pineal gland',
    regulatoryStatus: 'Research peptide — not FDA-approved',
    researchLevel: 'moderate',
    isResearchOnly: true,
    summary: 'Pineal-derived tetrapeptide (Ala-Glu-Asp-Gly). Activates telomerase, extends telomere length, and regulates melatonin and circadian rhythms. One of the most researched anti-aging peptides in Russian geroscience literature.',
    mechanism: 'Telomerase enzyme activation. Telomere length extension. Pineal melatonin synthesis regulation. Antioxidant pathway activation. Circadian rhythm normalization.',
    benefits: [
      'Telomere extension (in vitro and animal data)',
      'Improved sleep quality via melatonin regulation',
      'Extended lifespan in multiple animal models',
      'Retinal function preservation',
      'Antioxidant and immune modulation',
    ],
    dosing: {
      typical: '5-10 mg/day SC for 10-20 day courses',
      range: '5-10 mg/day',
      frequency: 'Daily during course periods',
      route: ['Subcutaneous'],
      cycle: '10-20 day courses repeated 1-2 times per year (geroscience protocol)',
      notes: 'Russian geroscience protocol: 10-20 days twice yearly. Some practitioners use 5 mg/day continuously. Bedtime dosing preferred.',
    },
    sideEffects: 'Well-tolerated in all available studies. No significant adverse events reported across decades of Russian research.',
    stacks: ['Epithalon + GHK-Cu (anti-aging combination)', 'Epithalon + Thymosin Alpha-1 (immune longevity protocol)', 'Epithalon + MOTS-c (longevity stack)'],
    humanEvidence: 'Russian clinical research spanning decades (Khavinson et al). Limited Western RCT data but extensive long-term safety record.',
    pkHalfLife: 'Approximately 30 minutes',
    bioavailability: 'SC: high',
    researchSources: 'Khavinson VKh et al, Bull Exp Biol Med 2003;135:590; Anisimov VN et al, Mech Ageing Dev 2003',
  },

  {
    id: 'thymosin_alpha1',
    name: 'Thymosin Alpha-1',
    fullName: 'Thymosin Alpha-1 (Zadaxin)',
    categoryTag: 'immune',
    category: 'Immune Modulation',
    icon: '🛡️',
    tagline: 'Endogenous thymic peptide — FDA-approved in 35+ countries',
    regulatoryStatus: 'FDA-approved (Zadaxin) in 35+ countries. US compoundable off-label.',
    researchLevel: 'high',
    isResearchOnly: false,
    summary: 'Endogenous thymic hormone that modulates T-cell differentiation and immune balance. Used for chronic hepatitis B/C, cancer immunotherapy adjuvant, and immune deficiency states. Strongest immune peptide with established clinical protocols.',
    mechanism: 'TLR2 and TLR9 agonism on dendritic cells. Th1 differentiation increase. NK cell activation. IL-2 and IFN-gamma production upregulation. Regulatory T-cell modulation.',
    benefits: [
      'Enhances T-cell immunity (Th1 response)',
      'Antiviral activity: hepatitis B/C, studied in COVID-19',
      'Cancer immunotherapy adjuvant',
      'Chronic fatigue and immune deficiency improvement',
      'Autoimmune condition modulation',
    ],
    dosing: {
      typical: '1.6 mg SC twice weekly (Zadaxin standard protocol)',
      range: '1.6-3.2 mg/week',
      frequency: 'Twice weekly',
      route: ['Subcutaneous'],
      cycle: '6-12 months for chronic conditions; shorter courses for acute immune support',
      notes: 'FDA dose for hepatitis: 1.6 mg SC twice weekly for 6 months. Anti-aging use: same dose, shorter cycles.',
    },
    sideEffects: 'Very well-tolerated. Injection site reactions only. Excellent clinical safety record across decades of use in 35+ countries.',
    stacks: ['Thymosin Alpha-1 + Epithalon (immune longevity protocol)', 'Thymosin Alpha-1 + BPC-157 (inflammation and immune support)'],
    humanEvidence: 'Multiple large RCTs for hepatitis B/C. Clinical approval in 35+ countries including Zadaxin designation. COVID-19 trial data emerging.',
    pkHalfLife: 'Approximately 2 hours',
    bioavailability: 'SC: approximately 100%',
    researchSources: 'Goldstein AL et al, Expert Opin Biol Ther 2009;9:593; Zhang Y et al, Clin Transl Immunology 2021',
  },

  {
    id: 'selank',
    name: 'Selank',
    fullName: 'Selank (TP-7)',
    categoryTag: 'neuro',
    category: 'Neuropeptide / Anxiolytic',
    icon: '🧠',
    tagline: 'Anxiolytic neuropeptide without dependence or sedation',
    regulatoryStatus: 'Registered drug in Russia. Research peptide in United States.',
    researchLevel: 'moderate',
    isResearchOnly: true,
    summary: 'Synthetic tuftsin analogue with anxiolytic, nootropic, and immunomodulatory effects. No addictive potential or benzodiazepine-like withdrawal. Acts simultaneously on GABA-A, serotonin, and BDNF pathways.',
    mechanism: 'GABA-A modulation without dependence or tolerance. Serotonin turnover increase. BDNF upregulation. Enkephalin degradation inhibition. IL-6 and IL-2 mRNA stabilization (immune modulation).',
    benefits: [
      'Anxiety reduction without sedation or dependence',
      'Nootropic effects: learning, memory, attention',
      'Mood stabilization and emotional regulation',
      'Immune modulation',
      'Neuroprotection',
    ],
    dosing: {
      typical: '250-500 mcg intranasal or SC, 1-2 times daily',
      range: '250-1000 mcg/day',
      frequency: 'Once or twice daily',
      route: ['Intranasal (preferred for CNS access)', 'Subcutaneous'],
      cycle: '2-4 weeks; can be used as needed for acute anxiety',
      notes: 'Intranasal preferred for rapid CNS penetration. Can be used situationally (pre-event anxiety) or as a course.',
    },
    sideEffects: 'Excellent tolerability profile. Mild sedation at higher doses. No withdrawal effects, no dependence liability.',
    stacks: ['Selank + Semax (cognitive plus anxiolytic balance)', 'Selank + BPC-157 (neuroprotection stack)'],
    humanEvidence: 'Russian clinical trials for anxiety conditions. Limited Western controlled trial data. Long clinical use record in Russia.',
    pkHalfLife: 'Approximately 15 minutes intranasal',
    bioavailability: 'Intranasal: approximately 90% CNS penetration',
    researchSources: 'Uchakina ON et al, Bull Exp Biol Med 2008;146:458; Zozulya AA et al, CNS Drug Rev 2001;7:143',
  },

  {
    id: 'semax',
    name: 'Semax',
    fullName: 'Semax (ACTH 4-10 analogue)',
    categoryTag: 'neuro',
    category: 'Neuropeptide / Cognitive',
    icon: '💡',
    tagline: 'BDNF-stimulating nootropic for focus and neuroprotection',
    regulatoryStatus: 'Registered drug in Russia. Research peptide in United States.',
    researchLevel: 'moderate',
    isResearchOnly: true,
    summary: 'Synthetic ACTH 4-10 analogue. Potent BDNF and NGF upregulator. Used for cognitive enhancement, stroke recovery, and neuroprotection. Stimulatory profile — morning use is preferred.',
    mechanism: 'BDNF and NGF upregulation. Melanocortin receptor activation. Dopaminergic and serotonergic enhancement. Brain antioxidant protection. Enkephalin degradation inhibition.',
    benefits: [
      'BDNF upregulation supporting neuroplasticity and memory',
      'Cognitive enhancement: attention, processing speed',
      'Stroke recovery support and neuroprotection',
      'Antidepressant and mood-elevating properties',
      'Energy and motivation enhancement',
    ],
    dosing: {
      typical: '200-600 mcg intranasal, 1-2 times daily in the morning',
      range: '100-1500 mcg/day',
      frequency: 'Once or twice daily — morning preferred',
      route: ['Intranasal (preferred)', 'Subcutaneous'],
      cycle: '2-4 weeks on, 1-2 weeks off to prevent tolerance',
      notes: 'Stimulatory — avoid evening dosing. Stack with Selank for balanced cognitive enhancement without overstimulation.',
    },
    sideEffects: 'Generally well-tolerated. Mild anxiety or overstimulation at higher doses. No serious adverse effects reported.',
    stacks: ['Semax + Selank (cognitive enhancement plus anxiolytic balance)', 'Semax + BPC-157 (neuroprotection combination)'],
    humanEvidence: 'Russian clinical trials for stroke recovery and cognitive conditions. Used as registered drug in Russia for decades. Limited Western RCT data.',
    pkHalfLife: 'Approximately 20 minutes intranasal',
    bioavailability: 'Intranasal: high CNS penetration',
    researchSources: 'Ashmarin IP et al, Neurochem Res 1997;22:1491; Shadrina MI et al, Dokl Biol Sci 2001;381:559',
  },

  {
    id: 'kpv',
    name: 'KPV',
    fullName: 'KPV Tripeptide (Lys-Pro-Val)',
    categoryTag: 'gut',
    category: 'Anti-Inflammatory / GI',
    icon: '🌿',
    tagline: 'Alpha-MSH fragment — targeted gut anti-inflammatory',
    regulatoryStatus: 'Research peptide — not FDA-approved',
    researchLevel: 'moderate',
    isResearchOnly: true,
    summary: 'C-terminal fragment of alpha-MSH. Potent intestinal anti-inflammatory with oral bioavailability — rare for a peptide. Best combined with BPC-157 for IBD, leaky gut, and NSAID-induced GI damage.',
    mechanism: 'MC1R and MC3R agonism. NF-kB, TNF-alpha, and IL-1beta inhibition. Intestinal permeability improvement. Direct colonic epithelium action. Mast cell stabilization.',
    benefits: [
      'IBD and Crohn\'s disease inflammation reduction',
      'Gut barrier and leaky gut improvement',
      'Systemic anti-inflammatory activity',
      'Wound healing properties',
    ],
    dosing: {
      typical: '100-500 mcg oral or SC, 1-2 times daily',
      range: '100-1000 mcg/day',
      frequency: 'Once or twice daily',
      route: ['Oral (bioavailable — rare for peptides)', 'Subcutaneous'],
      cycle: '4-8 weeks for gut healing indications',
      notes: 'Oral route is viable and practical for GI indications. Combine with BPC-157 for superior gut healing. Take on empty stomach.',
    },
    sideEffects: 'Very limited adverse event data available. Appears well-tolerated in all studies.',
    stacks: ['KPV + BPC-157 (gut healing synergy — most common GI stack)'],
    humanEvidence: 'Limited — primarily in vitro and animal studies. Clinical use growing rapidly based on mechanism and safety profile.',
    pkHalfLife: 'Approximately 1 hour',
    bioavailability: 'Oral: moderate; SC: high',
    researchSources: 'Dalmasso G et al, PLoS ONE 2008;3:e1817; Kannengiesser K et al, Regul Pept 2008;150:100',
  },

  {
    id: 'motsc',
    name: 'MOTS-c',
    fullName: 'Mitochondrial-Derived Peptide MOTS-c',
    categoryTag: 'mitochondrial',
    category: 'Mitochondrial / Metabolic',
    icon: '⚡',
    tagline: 'Mitochondrial genome-encoded peptide for metabolic health',
    regulatoryStatus: 'Research peptide — not FDA-approved',
    researchLevel: 'emerging',
    isResearchOnly: true,
    summary: 'Mitochondria-derived peptide encoded in the mitochondrial genome. Naturally declines with age. Regulates insulin sensitivity, mitochondrial biogenesis, and exercise adaptation. One of the most exciting emerging longevity peptides.',
    mechanism: 'AMPK activation. Folate cycle and purine biosynthesis regulation. Nuclear gene expression for metabolic adaptation. Mitochondrial biogenesis stimulation. Insulin sensitization via GLUT4 translocation.',
    benefits: [
      'Improved insulin sensitivity and glucose metabolism',
      'Mitochondrial biogenesis stimulation',
      'Enhanced exercise performance and endurance',
      'Anti-aging metabolic effects',
      'Potential applications in T2DM management',
    ],
    dosing: {
      typical: '5-10 mg/week SC',
      range: '5-10 mg/week',
      frequency: 'Once or twice weekly',
      route: ['Subcutaneous'],
      cycle: '4-8 weeks; best results when combined with regular exercise',
      notes: 'Dose on training days for best results. Synergistic with exercise via AMPK activation. Monitor glucose in diabetic patients.',
    },
    sideEffects: 'Limited safety data. Appears well-tolerated in available animal and early human studies.',
    stacks: ['MOTS-c + SS-31 (mitochondrial dual stack)', 'MOTS-c + Epithalon (longevity protocol)'],
    humanEvidence: 'Early human data available. Strong AMPK and metabolic effects in animal studies. Human aging decline well-documented.',
    pkHalfLife: 'Approximately 1-2 hours',
    bioavailability: 'SC: high',
    researchSources: 'Lee C et al, Cell Metab 2015;21:443; Reynolds JC et al, Nat Aging 2021;1:747',
  },

  {
    id: 'ss31',
    name: 'SS-31',
    fullName: 'Elamipretide (SS-31)',
    categoryTag: 'mitochondrial',
    category: 'Mitochondrial',
    icon: '🔋',
    tagline: 'Cardiolipin-targeting peptide for mitochondrial restoration',
    regulatoryStatus: 'Investigational — Phase III completed, NDA submitted for Barth syndrome',
    researchLevel: 'high',
    isResearchOnly: true,
    summary: 'Targets cardiolipin on the inner mitochondrial membrane. The highest-evidence mitochondrial peptide. Restores cristae architecture, reduces electron leak, and improves ATP synthesis. Strong evidence for heart failure and skeletal muscle restoration.',
    mechanism: 'Cardiolipin binding on inner mitochondrial membrane. Cristae structure stabilization. Electron transport chain efficiency increase. Mitochondrial ROS reduction. ATP synthesis restoration. Prevents mitochondrial permeability transition pore opening.',
    benefits: [
      'Mitochondrial function restoration',
      'Cardiac function improvement in HFpEF',
      'Age-related skeletal muscle dysfunction reversal',
      'Ischemia-reperfusion injury protection',
      'Energy and fatigue improvement',
    ],
    dosing: {
      typical: '0.05-0.25 mg/kg SC or IV (clinical trial dosing)',
      range: '0.05-0.5 mg/kg',
      frequency: 'Daily or as directed by physician',
      route: ['Subcutaneous', 'Intravenous (clinical trials only)'],
      cycle: 'Ongoing; requires physician supervision for dosing and monitoring',
      notes: 'Clinical trial doses range from 0.05 to 0.25 mg/kg. Physician supervision required. NDA submitted for Barth syndrome.',
    },
    sideEffects: 'Well-tolerated in Phase II/III trials. Injection site reactions are the primary adverse effect. No systemic toxicity at clinical doses.',
    stacks: ['SS-31 + MOTS-c (mitochondrial dual stack for comprehensive mitochondrial support)'],
    humanEvidence: 'Multiple Phase II/III clinical trials completed. NDA submitted to FDA for Barth syndrome. Strong human trial data for HFpEF and skeletal muscle.',
    pkHalfLife: 'Approximately 1 hour',
    bioavailability: 'SC: high; selectively concentrates in mitochondria',
    researchSources: 'Szeto HH, Pharm Res 2011;28:2669; Karhu ST et al, Redox Biol 2023;63:102781',
  },

  {
    id: 'glutathione',
    name: 'Glutathione',
    fullName: 'Reduced Glutathione (GSH)',
    categoryTag: 'anti_aging',
    category: 'Antioxidant / Detoxification',
    icon: '🌟',
    tagline: 'Master antioxidant tripeptide produced endogenously in every cell',
    regulatoryStatus: 'FDA-approved for IV use (Reata Pharmaceuticals). Widely compoundable for IV, IM, and nebulized routes.',
    researchLevel: 'high',
    isResearchOnly: false,
    summary: 'Glutathione (GSH) is a small tripeptide (gamma-Glutamyl-Cysteinyl-Glycine) produced endogenously in every cell. The most abundant intracellular antioxidant. Declines significantly with age, chronic disease, and toxin exposure. Supports redox defense, detoxification, and immune function.',
    mechanism: 'Primary redox buffer: GSH donates an electron to neutralize reactive oxygen species, becoming oxidized GSSG, then recycled by glutathione reductase. Phase II liver detoxification via glutathione S-transferase conjugation. Supports T-cell proliferation and NK cell activity. Regenerates vitamins C and E.',
    benefits: [
      'Master intracellular antioxidant and free radical scavenger',
      'Liver detoxification support (Phase II conjugation)',
      'Immune function enhancement: T-cell and NK cell support',
      'Skin brightening and melanin regulation',
      'Mitochondrial protection from oxidative damage',
      'Neuroprotection: studied in Parkinson\'s disease',
      'Athletic recovery: reduces exercise-induced oxidative stress',
    ],
    dosing: {
      typical: '600-1200 mg IV push or slow IV infusion',
      range: '400-2400 mg per session',
      frequency: '1-3 times per week IV; daily nebulized or liposomal oral',
      route: ['Intravenous (highest bioavailability)', 'Intramuscular', 'Nebulized (pulmonary)', 'Liposomal oral', 'Sublingual'],
      cycle: 'Continuous use acceptable; IV courses 4-8 weeks then reassess',
      notes: 'IV glutathione has the highest bioavailability. Oral glutathione has poor absorption unless liposomal. N-acetylcysteine (NAC) is a reliable oral precursor. Injectable glutathione is NOT FDA-approved for any indication — injectable glutathione is NOT FDA-approved for any indication.',
    },
    sideEffects: 'Injectable glutathione is NOT FDA-approved for any indication. Subcutaneous injection is NOT an established clinical route for glutathione. IV administration: generally well-tolerated at clinical doses. Rare: anaphylaxis (very rare), bronchospasm with nebulized use. High-dose IV: nausea, abdominal cramping, transient zinc depletion with long-term use. Skin lightening is dose-dependent and reversible.',
    stacks: ['Glutathione + Vitamin C IV (classic antioxidant IV protocol)', 'Glutathione + NAC oral (oral precursor + reduced form)', 'Glutathione + Alpha-lipoic acid (recycling synergy)', 'Glutathione + BPC-157 (gut health and antioxidant protection)'],
    humanEvidence: 'Strong evidence for IV use in liver disease, heavy metal detoxification, and Parkinson\'s (Sechi G et al). Skin brightening RCTs conducted in Asia. Exercise recovery human data available.',
    pkHalfLife: 'IV: rapid redistribution, intracellular half-life hours to days',
    bioavailability: 'IV: approximately 100%; liposomal oral: 30-50%; standard oral: less than 5%; nebulized: high pulmonary delivery',
    researchSources: 'Kern JK et al, Neuroimmunol Neuroinflammation 2018; Sechi G et al, Lancet 1996;347:777; Allen J et al, Altern Med Rev 2011;16:152',
  },

];

// ── Text summary for AI context injection ────────────────────────────────────
export const PEPTIDE_CONTEXT = PEPTIDE_KNOWLEDGE_BASE.map(p => {
  const d = p.dosing;
  return [
    `=== ${p.name} (${p.fullName}) ===`,
    `Category: ${p.category} | Status: ${p.regulatoryStatus} | Evidence: ${p.researchLevel}`,
    `Summary: ${p.summary}`,
    `Mechanism: ${p.mechanism}`,
    `Benefits: ${(p.benefits || []).join('; ')}`,
    `Dosing: ${d.typical || ''} | Range: ${d.range || ''} | Frequency: ${d.frequency || ''} | Route: ${(d.route || []).join(', ')} | Cycle: ${d.cycle || ''} | Notes: ${d.notes || ''}`,
    `Side Effects: ${p.sideEffects}`,
    `Common Stacks: ${(p.stacks || []).join('; ')}`,
    `Human Evidence: ${p.humanEvidence}`,
    `PK: Half-life ${p.pkHalfLife || 'unknown'} | Bioavailability: ${p.bioavailability || 'unknown'}`,
    `Sources: ${p.researchSources || 'See literature'}`,
    '',
  ].join('\n');
}).join('\n');

export default PEPTIDE_KNOWLEDGE_BASE;
